config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    resources :comments
  end
  root "blogs#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    #Associations
    has_many :comments, dependent: :destroy

    #Validations
    validates :title, presence: true
    validates :content, presence: true 
    validates :publisher, presence: true  

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blog = Blog.new
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
    @comment = Comment.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to @blog
    else
      flash[:notice] = "Something wrong happened"
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to root_path
  end

  private 

  def blog_params
    params.require(:blog).permit(:title, :content, :publisher)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_or_int_instances, except:[:index, :new]
  
  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def show
  end

  def create
    @comment = @blog.comments.create(comments_params)
    redirect_to blog_path(@blog)
  end

  def edit
  end

  def update
    if @comment.update_attributes(comments_params)
      redirect_to blog_path(@blog)
    else
      render 'edit'
    end
  end

  def destroy
    if @comment.destroy
      redirect_to blog_path(@blog)
    else
      render 'edit'
    end
  end

  private
  def comments_params
    params.require(:comment).permit(:commenter, :comment_text)
  end

  def find_or_int_instances
    @blog = Blog.find(params[:blog_id])
    if params[:id].present?
      @comment = Comment.find(params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blogs/_form.html.erb
<div class="container">
<%= form_for @blog, :html => {:class => "form-horizontal center"} do |f| %>
<h2 class="col-md-8">All Blogs</h2>
  <div class="form-group p-0">
    <%= f.label :title, "Title:", class: "col-md-4 control-label" %>
    <div class="col-md-8">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content, "Content:", class: "col-md-4 control-label" %>
    <div class="col-md-8">
      <%= f.text_area :content, class: "form-control", rows: 10 %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :publisher, "Publisher:", class: "col-md-4 control-label" %>
    <div class="col-md-8">
      <%= f.text_field :publisher, class: "form-control" %>
    </div>
  </div>
    <div class="form-group col-md-8"><%= f.submit "Submit", class: "btn btn-default btn-outline-primary" %></div>
<% end %>
</div>

app/views/blogs/edit.html.erb
<%= render "form"%>

app/views/blogs/index.html.erb
<% if current_page?(root_path) %>
   <% @blogs.each do |blog| %>
   <div class="container mt-5 w-75">
      <div class="jumbotron">
        <h1 class="display-4"><%= blog.title.titleize %></h1>
        <p class="lead"><%= blog.content %></p>
        <hr class="my-4">
        <p>posted on : <%= blog.created_at.strftime("%B %d, %Y") %></p>
        <p class="lead">
           <%= link_to "Show", blog_path(blog), class:"btn btn-primary btn-sm" %></a>
           <%= link_to "Edit", edit_blog_path(blog), class:"btn btn-success btn-sm" %></a>
           <%= link_to "Delete", blog_path(blog), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %></a>
        </p>
    </div>
   </div>
   <% end %> 
<% else %> 
<%= render "form" %>
<% end %>

app/views/blogs/show.html.erb
<div class="container mt-4 w-75">
  <div class="jumbotron">
    <h1 class="display-4"><%= @blog.title %></h1>
    <p class="lead"><%= @blog.content %></p>
    <hr class="my-4">
    <p>posted on : <%= @blog.created_at.strftime("%B %d, %Y") %></p>
    <p class="lead">
      <%= link_to "Edit",  edit_blog_path(@blog), class:"btn btn-success btn-sm" %></a>
      <%= link_to "Delete", blog_path(@blog), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %></a>
    </p>
  </div>

  <% if @blog.comments.present? %>
    <div class="card mb-4" style="width: 100%;">
      <div class="card-body">
        <% @blog.comments.limit(3).each do |comment| %>
          <h5 class="card-title"><%= comment.commenter %></h5>
          <p class="card-text"><%= comment.comment_text %></p>
          <p>posted on : <%= comment.created_at.strftime("%B %d, %Y") %></p>
          <p class="lead">
            <%= link_to "Edit",  edit_blog_comment_path(@blog, comment), class:"btn btn-success btn-sm" %></a>
            <%= link_to "Delete", blog_comment_path(@blog, comment), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %></a>
          </p>
          <hr class="my-4">
        <% end %>
      </div>
   </div>
  <%end %>
  <h2>Add Comment</h2>
  <%= render 'comments/form'%>
</div>

app/views/comments/_form.html.erb
<%= form_for([@blog, @comment]) do |form| %>
  <p>
    <%= form.label :commenter, class: "col-md-4 control-label" %><br>
    <%= form.text_field :commenter, class: "form-control" %>
  </p>
  <p>
    <%= form.label :comment_text, class: "col-md-4 control-label" %><br>
    <%= form.text_area :comment_text, class: "form-control" %>
  </p>
  <p>
  <%= form.submit "Submit", class: "btn btn-default btn-outline-primary" %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<div class="container mt-4 w-50">
  <%= render 'form' %>
</div>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
     <%= link_to "Blogger", root_path, :class => "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to "Home", root_path, :class => "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Post", blogs_path, :class => "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>

  <div class="container-fluid"><%= yield %></div>
  </body>
</html>